### PR TITLE
Inherit tags from nodes for modular pipelines

### LINKED ISSUE #795: How to best display tags with modular pipelines
## Description

Kedro-viz doesn't filter on tags for modular pipeline nodes. If you add a tag on the modular pipeline and then you filter by that tag on Kedro-viz, the modular pipeline doesn't show on the kedro viz flow chart. 

kedro-viz-tag-issue

## Steps to Reproduce

1. User tags something, e.g. with `data-processing`
2. The modular pipeline has data-processing nodes
3. The user specifically selects the `data-processing` tag and deselects the other tags, if present
4. The modular pipeline node disappears
5. The other child nodes that are visible on the flowchart

## Expected Result
You should still be able to see the modular pipeline node if required and group those child nodes within it.

## Actual Result
Couldn't see the modular pipeline node and everything was expanded out.

## Your Environment
Include as many relevant details as possible about the environment you experienced the bug in:

* Web browser system and version:
* Operating system and version:
* NodeJS version used (if relevant):
* Kedro version used (if relevant):
* Python version used (if relevant):

## Checklist
- [x] Include labels so that we can categorise your issue

### PR DESCRIPTION
**Pull request by rashidakanchwala**
## Description

Resolves #795 

## Development notes

We tried solving this issue in the backend but the way modular pipelines is computed in the backend is very complex. I thought maybe we can try solving it in the FE using selectors. 

In this PR, we have a new selector called getTagsforNodesAndModularPipelines.This selector identifies nodes associated with specific tags and then propagates these tags to the corresponding modular pipeline(s) (nested as well) for each node.

## QA notes

I have also added some tags to the demo project so we can test this. 

## Checklist

- [ ] Read the [contributing](/CONTRIBUTING.md) guidelines
- [ ] Opened this PR as a 'Draft Pull Request' if it is work-in-progress
- [ ] Updated the documentation to reflect the code changes
- [ ] Added new entries to the `RELEASE.md` file
- [ ] Added tests to cover my changes

<a href="https://gitpod.io/#https://github.com/kedro-org/kedro-viz/pull/1542"></a>

### CODE REVIEW

File: src/selectors/nodes.js [hunk 1]
```diff
@@ -42,17 +42,47 @@ export const getGraphNodes = createSelector(
     }, {})
 );
 
+/**
+ * Retrieves tags associated with both nodes and their corresponding modular pipelines.
+ */
+export const getTaggedNodesAndModularPipelines = createSelector(
```
Comment (ravi-kumar-pilla) [inline src/selectors/nodes.js:48]: can we rename this to getTagsForNodesAndModularPipelines ?

**Review by ravi-kumar-pilla — APPROVED** [review]
This looks good. I do not see any lag in fetching tags but if we decide to update tags on FE, this should be good. I left a [Nit] comment for a method name but its non blocking.

**Review by SajidAlamQB — APPROVED** [review]
This makes more sense in the FE than in BE I am happy to go with this solution. 👍

File: src/selectors/nodes.js [hunk 2]
```diff
@@ -42,17 +42,47 @@ export const getGraphNodes = createSelector(
     }, {})
 );
 
+/**
+ * Retrieves tags associated with both nodes and their corresponding modular pipelines.
+ */
+export const getTagsforNodesAndModularPipelines = createSelector(
```
Comment (tynandebold) [inline src/selectors/nodes.js:48]:
```suggestion
export const getTagsForNodesAndModularPipelines = createSelector(
```

File: src/selectors/nodes.js [hunk 3]
```diff
@@ -42,17 +42,47 @@ export const getGraphNodes = createSelector(
...
+  [getNodeTags, getNodeModularPipelines],
+  (nodeTags, nodeModularPipelines) => {
+    const updatedNodeTags = { ...nodeTags };
+
+    Object.entries(nodeTags)
+      .filter(([, tags]) => tags.length > 0)
+      .forEach(([nodeID, tags]) => {
+        const modularPipelineIDs = nodeModularPipelines[nodeID] || [];
+        modularPipelineIDs.forEach((modularPipelineID) => {
```
Comment (tynandebold) [inline src/selectors/nodes.js:57]:
```suggestion
        const modularPipelineIDs = nodeModularPipelines[nodeID] || [];
        
        modularPipelineIDs.forEach((modularPipelineID) => {
```

**Review by tynandebold — APPROVED** [review]
Looks good and works well!

Two small nit comments from me. Also, make sure to sign your commits and make sure the Cypress tests are passing. For some reason, they're failing on your branch.
