### PR TITLE
 [Fix] Change Types on Metadata Side Panel

### LINKED ISSUE #752: [FE] Change `Types` on Metadata Side Panel
(transfer from Jira, created by @yetudada)

- We still have a mismatch with how terms on Kedro-Viz vs Kedro are called and one of the ways it shows itself it on the Metadata Side Panel.
- When you open the metadata side panel and see the `Type` entry we refer to `data` instead of `dataset` and `task` instead of `node`.
- This issue focuses on updating those entries: change `type: task` to `type: node` for Kedro Node node and remove `type: data` for dataset node. `type: params` remains unchanged.

Screenshot 2021-07-06 at 16 55 37

### PR DESCRIPTION
**Pull request by studioswong**
## Description

resolves #752 . 

## Development notes

I have added a function to translate the naming of the different types of nodes on the FE to return the desired naming. ( The BE still returns the different types of node as `task`, `data` and `params`, while we want to ensure the nodes are displayed as `node`, `dataset` and `params`. 

I have also updated a variable naming ( I have kept `isTaskNode` as it is to avoid confusion for `isNodeNode`), as well as any related tests. 

## QA notes

The node type on the metadata panel should have the newly updated node type naming. 

## Checklist

- [x] Read the [contributing](/CONTRIBUTING.md) guidelines
- [ ] Opened this PR as a 'Draft Pull Request' if it is work-in-progress
- [ ] Updated the documentation to reflect the code changes
- [x] Added new entries to the `RELEASE.md` file
- [ ] Added tests to cover my changes

<a href="https://gitpod.io/#https://github.com/kedro-org/kedro-viz/pull/852"></a>

### CODE REVIEW

File: src/components/metadata/metadata.js [hunk 1]
```diff
@@ -36,7 +36,7 @@ const MetaData = ({
   // Hide plot modal when selected metadata changes
   useEffect(() => onTogglePlotModal(false), [metadata, onTogglePlotModal]);
   const isTaskNode = metadata?.type === 'task';
```
Comment (tynandebold) [inline src/components/metadata/metadata.js:38]: Maybe add a comment after this line to say that this really should be `isNodeNode`, though this `isTaskNode` naming is better, hence we're leaving it, as you said in your PR description?

File: src/components/metadata/metadata.js [hunk 2]
```diff
@@ -53,6 +53,17 @@ const MetaData = ({
...
 
+  // translates the naming for the different types of nodes
+  const translateMetadataType = (metaDataType) => {
+    if (metaDataType === 'task') {
+      return 'node';
+    }
+    if (metaDataType === 'data') {
+      return 'dataset';
+    }
+    return metaDataType;
```
Comment (tynandebold) [inline src/components/metadata/metadata.js:64]: This could be a good place to use `switch`.

**Review by tynandebold — APPROVED** [review]
Looks great, thanks for this.

Just a couple of small things from me, though nothing blocking.

File: src/components/metadata/metadata.js (hunk 1 above)
Comment (AntonyMilneQB) [reply src/components/metadata/metadata.js:38]: I'd actually leave the `isDataNode` as it was called rather than renaming to `isDatasetNode`. That way everything is consistent and `isTaskNode` would be "correct" already. The `isXNode` has `X` consistent with the backend naming scheme. This way the only inconsistency is the way the names appear on the screen, which is all handled by `translateMetadataType`.

**Review by AntonyMilneQB — APPROVED** [review]
Looks good, just a small comment on naming!

I really wish we'd called the generic "node" a "vertex" instead and then had 3 different types of vertex: node, dataset, parameter. But that's not for now 😅

File: src/components/metadata/metadata.js (hunk 1 above)
Comment (studioswong) [reply src/components/metadata/metadata.js:38]: yea @AntonyMilneQB I agree on this, and was think the same thing, so you kind of confirmed my thoughts!

I'll just revert it back to `isDataNode`.

**Review by rashidakanchwala — APPROVED** [review]
LGTM! thanks @studioswong
